import Head from "next/head";
import Link from "next/link";

import { type InferModel, eq } from "drizzle-orm";

import { db } from "~/database";
import { users } from "~/database/schema";
import Hello from "../components/Hello";
import { SignIn } from "~/components/SignIn";
import { getSession } from "~/lib/auth/session";
import { SignOut } from "~/components/SignOut";

export default async function Home() {
  const session = await getSession();

  let user: InferModel<typeof users>[] = [];

  if (session?.user.name) {
    user = await db
      .select()
      .from(users)
      .where(eq(users.name, session?.user.name))
      .limit(1);
  }

  return (
    <>
      <Head>
        <title>Next Stack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background-black flex min-h-screen flex-col items-center justify-center bg-slate-950">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            {user[0] && <>Welcome User: {user[0]?.name} </>}
          </h1>
          <Hello />
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-lg bg-slate-800 p-4 text-slate-50 hover:bg-slate-700"
              href="https://orm.drizzle.team/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Drizzle ORM</h3>
              <div className="text-lg">
                Drizzle ORM is a TypeScript ORM for SQL databases designed with
                maximum type safety in mind.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-lg bg-slate-800 p-4 text-slate-50 hover:bg-slate-700"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Authentication</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          {session?.user && (
            <>
              <h4 className="text-lg font-bold text-slate-50">
                Your Session Data
              </h4>
              <code className="rounded-lg bg-gray-800 p-4 pl-6 text-left text-sm text-white sm:text-base">
                <div>
                  <span className="shrink-0 text-gray-500">name: </span>
                  <span>{session?.user.name}</span>
                </div>
                <div>
                  <span className="shrink-0 text-gray-500">email: </span>
                  <span>{session?.user.email}</span>
                </div>
              </code>
            </>
          )}
          <div className="flex flex-col items-center gap-2 text-slate-50">
            {!session ? <SignIn /> : <SignOut />}
          </div>
        </div>
      </main>
    </>
  );
}
